### ISSUE TITLE
Screenshot Not Same

### ISSUE THREAD

**Issue by ceteongvanness** [amynic/AINights#8]
when I select the custom vision, the screenshot are not same as current for the logic app, which one should see select?
here is the image URL: [Custom Vision](https://github.com/ceteongvanness/eventdemo/blob/master/Global%20AI%20Night%20Sept%202019/Images/P1-42.png)

Please let me know which one should i choose. Thank you.

**Comment by amynic** [comment]
Hi @ceteongvanness  thanks for the note above - I have just created a blank logic app and added the custom vision logic app step and I see the same as the screenshot in the documentation - you should select "Classify an Image URL (preview)" - could you explain or post a screenshot of the options you are seeing so I can dive into this further?

**Comment by ceteongvanness** [comment]
After I select the Classify an Image URL (preview)
Where can I get the Connection name and Site URL?
here is the screenshot: [Custom Vision](https://github.com/ceteongvanness/eventdemo/blob/master/Global%20AI%20Night%20Sept%202019/Images/P1-44.png)

**Comment by amynic** [comment]
Apologies I misunderstood the question and found the documentation error - I will update shortly with the new layout

**Comment by amynic** [comment]
updated the docs images to update the custom vision logic app connector choices and where you get them from. Commit: https://github.com/amynic/AINights/commit/cb854c76a872f0318a4ec433ac7ba68aba9c1284 

If you are happy this has answered the missing docs - please let me know and I will close the issue

**Comment by amynic** [comment]
Closing this issue as updated
